### ISSUE TITLE
sun.misc.Cleaner NoClassDefFoundError using JDK9

### ISSUE THREAD

**Issue by nullterminated** [RuedigerMoeller/InstrinsicReactJSX#3]
localhost:8080 refuses connection

$ java -jar target/bundle.jar 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.nustaq.serialization.FSTClazzInfo (file:/home/alarm/projects/InstrinsicReactJSX/target/bundle.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of org.nustaq.serialization.FSTClazzInfo
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/Cleaner
	at org.nustaq.offheap.bytez.malloc.MMFBytez.init(MMFBytez.java:59)
	at org.nustaq.offheap.bytez.malloc.MMFBytez.<init>(MMFBytez.java:38)
	at org.nustaq.offheap.FSTBinaryOffheapMap.resetMem(FSTBinaryOffheapMap.java:143)
	at org.nustaq.offheap.FSTBinaryOffheapMap.initFromFile(FSTBinaryOffheapMap.java:99)
	at org.nustaq.offheap.FSTBinaryOffheapMap.<init>(FSTBinaryOffheapMap.java:76)
	at org.nustaq.offheap.FSTCodedOffheapMap.<init>(FSTCodedOffheapMap.java:41)
	at org.nustaq.offheap.FSTSerializedOffheapMap.<init>(FSTSerializedOffheapMap.java:46)
	at org.nustaq.offheap.FSTAsciiStringOffheapMap.<init>(FSTAsciiStringOffheapMap.java:66)
	at org.nustaq.offheap.FSTAsciiStringOffheapMap.<init>(FSTAsciiStringOffheapMap.java:81)
	at sample.reactmaterial.PersistanceDummy.<init>(PersistanceDummy.java:18)
	at sample.reactmaterial.ReactMaterialUITestApp.<init>(ReactMaterialUITestApp.java:27)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.base/java.lang.Class.newInstance(Class.java:558)
	at org.nustaq.kontraktor.impl.ActorsImpl.makeProxy(ActorsImpl.java:69)
	at org.nustaq.kontraktor.impl.ActorsImpl.newProxy(ActorsImpl.java:124)
	at org.nustaq.kontraktor.impl.ActorsImpl.newProxy(ActorsImpl.java:110)
	at org.nustaq.kontraktor.Actors.AsActor(Actors.java:187)
	at sample.reactmaterial.ReactMaterialUITestApp.main(ReactMaterialUITestApp.java:88)
Caused by: java.lang.ClassNotFoundException: sun.misc.Cleaner
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 21 more

**Comment by RuedigerMoeller** [comment]
yes, the sample makes use of memory mapped files (of fst-serialization). Currently I don't have time to port this, will start once the JDK 9 ecosystem is more stable and functional complete (currently there seems to be no way to unmap mmapped memory, which is a no go).

**Comment by RuedigerMoeller** [comment]
should work with jdk 11
