### ISSUE TITLE
Followed steps to run via the command line and got the following two types of issues. How do I get past these?

### ISSUE THREAD

**Issue by damcard** [RuedigerMoeller/InstrinsicReactJSX#7]
First I see this in the log when I try to go to the site:

I 09:28:37:729;DispatcherThread 8;JNPM  installing 'asap@2.0.6' in C:\Users\sadmc\atos\workspace\InstrinsicReactJSX\.\src\main\web\node_modules.
W 09:28:38:338;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:429;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:433;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:455;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:463;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:463;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:463;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:470;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:472;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:489;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:493;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:513;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:526;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:526;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:528;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:533;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:533;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:549;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:553;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:558;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:558;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:560;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:560;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:560;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:571;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:584;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:584;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:589;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:604;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:612;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:612;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:614;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:614;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:647;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:649;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:657;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:658;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:662;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:666;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:670;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:724;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:741;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:761;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:761;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:899;DispatcherThread 8;JNPM  distribution is empty or error 429
W 09:28:38:977;DispatcherThread 8;JNPM  distribution is empty or error 429

After that I see a bunch of these:

I 09:28:39:577;XNIO-1 task-2;JSXIntrinsicTranspiler  kontraktor-client not found. installing .. 'kontraktor-client'
W 09:28:39:610;DispatcherThread 8;JNPM  distribution is empty or error 429
org.nustaq.kontraktor.AwaitException: 429
        at org.nustaq.kontraktor.Promise.awaitHelper(Promise.java:453)
        at org.nustaq.kontraktor.Promise.await(Promise.java:393)
        at org.nustaq.kontraktor.webapp.transpiler.JSXIntrinsicTranspiler.resolveImportSpec(JSXIntrinsicTranspiler.java:419)
        at org.nustaq.kontraktor.webapp.transpiler.JSXIntrinsicTranspiler.processJSX(JSXIntrinsicTranspiler.java:260)
        at org.nustaq.kontraktor.webapp.transpiler.JSXIntrinsicTranspiler.transpile(JSXIntrinsicTranspiler.java:43)
        at org.nustaq.kontraktor.webapp.javascript.DynamicResourceManager.getResource(DynamicResourceManager.java:181)
        at io.undertow.server.handlers.resource.DefaultResourceSupplier.getResource(DefaultResourceSupplier.java:39)
        at io.undertow.server.handlers.resource.ResourceHandler$1.handleRequest(ResourceHandler.java:205)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:332)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:812)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
E 09:28:39:645;XNIO-1 task-2;JSXIntrinsicTranspiler  jnpm install timed out. Check Proxy JVM settings, internet connectivity or just retry

I have a good internet connection. Thanks

**Comment by RuedigerMoeller** [comment]
better use npm to install js-packages. 

JNPM frequently lags behind changes in npm registry, but it will be there within some month :)
